spin = (-1+round(random(1))*2)*random(5)
done = false
sound = false
startSpeed = 0.1
bounce = 1
direction = objPlayer.lookDir + 90 + random_range(10, -8)
image_speed = 0
friction = 0.1
speed = random_range(3, 9)
image_angle = objPlayer.lookDir
depth = 550